### ISSUE TITLE
[ Bug ] Endless redirect loop on trixiebot.com when visiting via HTTP (not HTTPS)

### ISSUE THREAD

**Issue by Calinou** [LonelessCodes/trixiebot#8]
**Before submitting I have:**
- [x] Made sure this is actual unintended behaviour.
- [x] Double checked `!help <command name>` (if this is command related) for potential misunderstandings.

**Describe the bug**
Not strictly related to the bot, but visiting http://trixiebot.com on Firefox 77 or Chromium 81 will cause the URL bar to turn into this, while displaying an empty page:

![image](https://user-images.githubusercontent.com/180032/85224122-44f59e00-b3c8-11ea-8942-816c74f7a86b.png)

This doesn't occur when browsing https://trixiebot.com.

**To Reproduce**
Visit http://trixiebot.com (*not* https://trixiebot.com, which works correctly).

**Expected behavior**
http://trixiebot.com should redirect to https://trixiebot.com.

**Comment by LonelessCodes** [comment]
Can reproduce on Chrome.

**Comment by LonelessCodes** [comment]
Fixed. Thank you for the issue.
